repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1"
    hooks:
      - id: mypy
        additional_dependencies:
          [
            "django-stubs[compatible-mypy]",
            "djangorestframework-stubs[compatible-mypy]",
            "drf-yasg",
            "django-debug-toolbar",
            "sentry_sdk",
            "psycopg",
            "boto3",
            "pyzipper",
            "openpyxl",
            "django-celery-results",
          ]
  - repo: https://github.com/python-poetry/poetry
    rev: "1.3.2"
    hooks:
      - id: poetry-check
      - id: poetry-lock
